import os
from dotenv import load_dotenv
load_dotenv()

# --- ENDPOINTS ---
BASE_URL_MESSAGES = "/api/messages"

# --- JSON FIELDS---
FIELD_STATUS = "status" 
FIELD_ERROR = "error"
FIELD_CODE = "code"
FIELD_MESSAGE = "message"
FIELD_DETAILS = "details"
FIELD_MESSAGE_ID = "message_id"
FIELD_SESSION_ID = "session_id"
FIELD_CONTENT = "content"
FIELD_SENDER = "sender"

# --- COMMON FIELD NAMES ---
VALID_SENDER = "user"
INVALID_SENDER = "bot"
CONTENT_VALID = "Hello World"
CONTENT_SHORT = "Hi"

# --- SESSIONS AND MESSAGES ---
SESSION_ID_VALID = "s100"
SESSION_ID_PAGINATION = "s200"
SESSION_ID_INVALID = "no-exist"
MESSAGE_ID_VALID = "m100"
MESSAGE_ID_INVALID_SENDER = "m101"

# --- HTTP STATUS ---
STATUS_BAD_REQUEST = 400
STATUS_CONFLICT = 409
STATUS_NOT_FOUND = 404
STATUS_INTERNAL_ERROR = 500
STATUS_CREATED = 201
STATUS_OK = 200
STATUS_UNAUTHORIZED = 401
STATUS_FORBIDDEN = 403
STATUS_TOO_MANY_REQUESTS = 429

# --- BUSSINES ERRORS ---
ERROR_CODE_INVALID_SENDER = "INVALID_SENDER"
ERROR_CODE_NOT_FOUND = "NOT_FOUND"
ERROR_CODE_MISSING_FIELD = "MISSING_FIELD"
ERROR_CODE_DUPLICATE_MESSAGE_ID = "DUPLICATE_MESSAGE_ID"
ERROR_CODE_SERVER = "SERVER_ERROR"
ERROR_CODE_UNAUTHORIZED = "UNAUTHORIZED"
ERROR_CODE_RATE_LIMIT = "RATE_LIMIT_EXCEEDED"

# --- GENERIC ERROR MESSAGES ---
GENERIC_SERVER_ERROR_MESSAGE = "Unexpected error while processing request"
ERROR_DETAIL_RATE_LIMIT = "Too many requests in a short period. Please try again later."

# --- STATUS RESPONSES ---
STATUS_ERROR_RESPONSE = "error"

# --- METADATA FIELDS ---
METADATA_WORD_COUNT_FIELD = "word_count"  # usado para validar metadata

# --- BADWORDS CONTENT ---
CONTENT_WITH_BADWORD = "hello badword"
FILTERED_WORD_REPLACEMENT = "***"

# --- AUTH ---
API_KEY = os.getenv("API_KEY")
API_KEY_HEADER = {"x-api-key": API_KEY}