# --- ENDPOINTS ---
BASE_URL_MESSAGES = "/api/messages"

# --- CAMPOS JSON ---
FIELD_STATUS = "status" 
FIELD_ERROR = "error"
FIELD_CODE = "code"
FIELD_MESSAGE = "message"
FIELD_DETAILS = "details"
FIELD_MESSAGE_ID = "message_id"
FIELD_SESSION_ID = "session_id"
FIELD_CONTENT = "content"
FIELD_SENDER = "sender"

# --- VALORES COMUNES ---
VALID_SENDER = "user"
INVALID_SENDER = "bot"
CONTENT_VALID = "Hello World"
CONTENT_SHORT = "Hi"

# --- SESIONES Y MENSAJES ---
SESSION_ID_VALID = "s100"
SESSION_ID_PAGINATION = "s200"
SESSION_ID_INVALID = "no-exist"
MESSAGE_ID_VALID = "m100"
MESSAGE_ID_INVALID_SENDER = "m101"

# --- ESTADOS HTTP ---
STATUS_BAD_REQUEST = 400
STATUS_CONFLICT = 409
STATUS_NOT_FOUND = 404
STATUS_INTERNAL_ERROR = 500
STATUS_CREATED = 201
STATUS_OK = 200

# --- ERRORES DE NEGOCIO ---
ERROR_CODE_INVALID_SENDER = "INVALID_SENDER"
ERROR_CODE_NOT_FOUND = "NOT_FOUND"
ERROR_CODE_MISSING_FIELD = "MISSING_FIELD"
ERROR_CODE_DUPLICATE_MESSAGE_ID = "DUPLICATE_MESSAGE_ID"
ERROR_CODE_SERVER = "SERVER_ERROR"

# --- MENSAJES DE ERROR GENÉRICOS ---
GENERIC_SERVER_ERROR_MESSAGE = "Unexpected error while processing request"

# --- ESTADOS DE RESPUESTA ---
STATUS_ERROR_RESPONSE = "error"

# --- CAMPOS DE METADATA ---
METADATA_WORD_COUNT_FIELD = "word_count"  # usado para validar metadata

# --- CONTENIDO CON MALAS PALABRAS ---
CONTENT_WITH_BADWORD = "hello badword"
FILTERED_WORD_REPLACEMENT = "***"
